### ISSUE TITLE
Block macro processor?

### ISSUE THREAD

**Issue by ringods** [oxidecomputer/react-asciidoc#11]
Hello @benjaminleonard, I was trying to see if I could integrate a block macro processor that could handle block macros representing a Github gist:

```adoc
gist::ringods/b0af5b527121b6b543ec[]
```

I added the following code:

```ts
import ReactEmbedGist from 'react-embed-gist';

const gist = function (this: Extensions.Registry) {
    this.blockMacro('gist', function () {
        let self = this;
        self.named('gist')
        self.process(function (parent, target, attrs) {
            return (<ReactEmbedGist gist={target}/>)
        })
    })
}

const ad = asciidoctor()
ad.Extensions.register(gist)
```

But when running, I get quite a stacktrace:

```
error - node_modules/react-embed-gist/main.js (2:222) @ eval
error - ReferenceError: self is not defined
    at __webpack_require__ (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/articles/[slug]/page-article.tsx:10:74)
    at (sc_client)/./src/app/articles/[slug]/page-article.tsx (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/app/articles/[slug]/page.js:3377:1)
    at __webpack_require__ (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/webpack-runtime.js:33:43)
null
error - node_modules/react-embed-gist/main.js (2:222) @ eval
error - ReferenceError: self is not defined
    at eval (webpack-internal:///(sc_client)/./node_modules/react-embed-gist/main.js:2:63)
    at (sc_client)/./node_modules/react-embed-gist/main.js (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/app/articles/[slug]/page.js:3461:1)
    at __webpack_require__ (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_client)/./src/app/articles/[slug]/page-article.tsx:10:74)
    at (sc_client)/./src/app/articles/[slug]/page-article.tsx (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/app/articles/[slug]/page.js:3377:1)
    at __webpack_require__ (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/webpack-runtime.js:33:43)
    at requireModule (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:135:32)
    at initializeModuleChunk (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:415:17)
    at readChunk (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:245:7)
    at renderLazyComponent (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8672:19)
    at renderElement (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8784:11)
    at renderNodeDestructiveImpl (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8862:11)
    at renderNodeDestructive (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8834:14)
    at renderNodeDestructiveImpl (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8893:11)
    at renderNodeDestructive (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8834:14)
    at retryTask (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9300:5)
    at performWork (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9367:7)
    at /Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8099:14
    at scheduleWork (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:78:3)
    at pingTask (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8098:5)
    at ping (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8131:14)
    at wakeChunk (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:287:5)
    at wakeChunkIfInitialized (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:294:7)
    at resolveModelChunk (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:356:5)
    at resolveModel (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:713:5)
    at processFullRow (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:813:9)
    at processBinaryChunk (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:825:5)
    at progress (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:887:5)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:509:9) {
  page: '/articles/backporting-packages-easily'
}
```

I'm clearly doing something wrong. Is it possible to register block macro processors returning a React component?

**Comment by benjaminleonard** [comment]
I'd be surprised if React worked in that context — and I think the extension expects you to return a block.

Like this: https://github.com/oxidecomputer/react-asciidoc/blob/08de4909b9451401dd0b1ffacbc60b93c1aba423/src/App.tsx#L20-L34

What you might be able to do, is convert the react component to html with the react render to string fn and use it as the content for a passthrough block.

This is ruby, but I wonder if you can do the same with `asciidoctor.js`, passing your rendered react as the content: https://docs.asciidoctor.org/asciidoctorj/latest/extensions/block-macro-processor/

**Comment by ringods** [comment]
I must have misunderstood the whole extension mechanism then. Will indeed create the appropriate block as return value.

**Comment by benjaminleonard** [comment]
Part of the challenge of this renderer is that once you drop below a certain part in the tree we lose the ability to navigate and have to rely on `asciidoctor.js` to generate the content. And the code that does that is quite complex due to all the substitutions. One day I'd like to recreate that though, so everything is rendered by React. Would make this renderer much more powerful.
